- hosts: webserver
  become: true
  become_user: root
  vars:
    item:
      - git
      - docker
  tasks:
   - name: install package on server
     yum:
      name: "{{item}}"
      state: present
   - name: start docker service
     service:
      name: docker
      state: started
   - name: clone the repo on server
     git:
      repo: https://github.com/rohitcheta/AnsibleDockerdemo.git
      dest: /tmp/myrepo
   - name: build image from dcokerfile
     command: chdir=/tmp/myrepo docker build -t myansible .
   - name: deploy the image
     command: docker run -d -P myansible
